/olx-clone
    /assets
        /css
            styles.css
        /js
            app.js
    /index.html
    /create_ad.html
/my_project
    /templates
        register.html
    /static
        /css
            styles.css
    /app.py
    /database.db
